### ISSUE TITLE
No aplicas completamente el paradigma de programación funcional

### ISSUE THREAD

**Issue by whitehatdevv** [AslanSN/aleatory-program#1]
https://github.com/AslanSN/aleatory-program/blob/38ea9f80d7589099a5b05354f5a22058a4f7de48/index.js#L22

## Introducción 

A pesar de este fallo que voy a comentarte más abajo, tengo que destacarte también que tu código está muy limpio y bastante bien organizado, lo documentas muy bien y presenta mucha organización, lo que demuestra que te preocupa hasta el mínimo detalle. Llevo muchos años en esta industria y los desarrolladores que se preocupan en que su código sea elegante encuentran un buen trabajo rápido, es algo que **no suele ser normal**. 
Sigue trabajando a este ritmo y cada vez más fuerte hasta que el bootcamp acabe y verás la transformación en conocimientos que lograrás.

## Fallo

Recuerda que la programación funcional consiste en separar todo lo máximo posible en funciones dejando cada función como responsable de una única cosa.
Si te fijas, en todas las funciones debes limpiar los arrays, y tu has hecho eso en cada función por separado. Mi pregunta es:
¿Por qué no crear una función cuya **única responsabilidad** sea limpiar un array dado como parámetro?

```js
function cleanArray(arr) {
   // implementa tu la función
}
```

PD: Más que una pregunta es una propuesta a modificación :)

## Normas

Mantenemos la conversación del Issue por aquí ya que a través de BreathCode no se puede, tu me avisas por Slack cuando pueda volver a revisarlo (no te olvides de cerrar el ISSUE)

**Comment by AslanSN** [comment]
Entonces, ¿tú me recomiendas que haga como en el segundo ejercicio que una función de alto rango reciba una function llamada `ifFunction` que llame a cleanArray dentro del bucle for?

Así:

`````` JavaScript
function stringTestForRandomIndex (array, ifFunction)
{
    let newString = '';
    //loop only letting pass the strings
    for (let i = 0; i < array.length; i++)
    {
          ifFunction(array)
    }
    ...
}
function cleanArray(arr){
    ...
    if (typeof array[getRandomIndexFromArray(array)] === "string"){
       ...
    }
    ...
}


``````

O directamente llamado, (en vez de usar ifFunction, llamar directamente a cleanArray)

**Comment by whitehatdevv** [comment]
Sí, digamos que sí, de todos modos mañana en clase voy a soltar más luz al respecto y en el coding-weekend de esta semana voy a entrar más en detalles acerca de cuando usarlos.
